#Available variables: ${player_playtime}
tablist_header: "${player_playtime}"
#Available variables: ${player_playtime}
tablist_footer: "${player_playtime}"
#Available variables: ${online_players}, ยง{max_players}
playercount_text: ""